[package]
name = "image-max-polling"
version = "0.1.0"
edition = "2024"
authors = ["Dr.Guo"]
license = "MIT"
repository = "https://github.com/spartajet/image-max-pooling"


[dependencies]
rayon = "1"

[dev-dependencies]
anyhow = "1"
image = "0.25"
